# Generated by Django 4.2.4 on 2023-09-04 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro'), ('pajaro', 'Pajaro'), ('pez', 'Pez'), ('otro', 'Otro')], default='gato', max_length=50)),
                ('nombreMascota', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('historia', models.CharField(max_length=3200)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenMascota', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['autor', '-fechaPublicacion'],
            },
        ),
    ]
