# Generated by Django 4.2.4 on 2023-09-07 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='historia',
            field=models.TextField(help_text='Ingresa la historia de la mascota (máximo 40 líneas).', validators=[django.core.validators.MaxLengthValidator(limit_value=3200, message='La historia no puede superar 40 líneas.')]),
        ),
    ]
