# Generated by Django 4.2.4 on 2023-09-09 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppPages', '0002_alter_mascota_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='mascota',
            field=models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro'), ('pajaro', 'Pajaro'), ('pez', 'Pez'), ('otro', 'Otro')], default='', max_length=50),
        ),
    ]
