# Generated by Django 4.2.4 on 2023-09-07 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.TextField(blank=True, help_text='La descripción de usted debe ser como máximo 40 líneas.', null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=3200, message='La descripción sobre usted no puede superar 40 líneas.')]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='linkPaginaWeb',
            field=models.URLField(blank=True, null=True),
        ),
    ]
